/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "exbmtlptnpivzjpkkafu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4Ym10bHB0bnBpdnpqcGtrYWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNjY3MTcsImV4cCI6MjA3OTg0MjcxN30.Noxuh-6aW0U9Gmpo3NmZeVk8Ht2RmyeD64o84J-QkO0"